In [2]:
import numpy as np

In [4]:
x = [5,6,7,8,88,22,4,5,66,78,11,45]
indices = np.arange(0,len(x))
x,indices, len(x)

([5, 6, 7, 8, 88, 22, 4, 5, 66, 78, 11, 45],
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 12)

In [7]:
np.random.shuffle(indices)
indices

array([11,  7, 10,  8,  2,  6,  0,  4,  3,  9,  1,  5])

In [10]:
x = np.array(x)
y = x[indices]
y

array([45,  5, 11, 66,  7,  4,  5, 88,  8, 78,  6, 22])