In [1]:
import numpy as np

In [2]:
x = np.array([5,4,1,9,10,11,13])
x

array([ 5,  4,  1,  9, 10, 11, 13])

In [3]:
idx = np.argsort(x)
idx

array([2, 1, 0, 3, 4, 5, 6], dtype=int64)

In [4]:
idx = idx[::-1]

In [5]:
idx

array([6, 5, 4, 3, 0, 1, 2], dtype=int64)

In [6]:
idx = idx[:3]
idx

array([6, 5, 4], dtype=int64)

In [7]:
shortened = x[idx]

In [8]:
shortened

array([13, 11, 10])