In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.datasets import load_iris

In [4]:
dataset = load_iris()

In [27]:
input = dataset.data
input

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [28]:
output = dataset.target
output

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [29]:
indices = np.arange(0,150)
np.random.seed(42)
np.random.shuffle(indices)

In [ ]:
rinput = input[indices]
routput = output[indices]

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0,
       1, 2, 0, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0,
       0, 1, 1, 2, 1, 2, 2, 1, 0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1,
       1, 2, 1, 2, 0, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2,
       0, 2, 0, 1, 2, 2, 1, 2, 1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [70]:
##70:30 split
x_train_set = rinput[:125,:]
y_train_set = routput[:125]
x_test_set = rinput[125:150,:]
y_test_set = routput[125:150]

In [71]:
##gaussian naive bayes
probabilties = {}
targets = np.unique(y_train_set)
for value in targets:
    probabilties[value] = np.sum(y_train_set == value) / len(y_train_set)
probabilties


{0: 0.36, 1: 0.336, 2: 0.304}

In [72]:
from sklearn.metrics import accuracy_score

In [73]:
def predictions(test_example):
    probs = {}
    for result in probabilties.keys():
        filtered_Data = x_train_set[y_train_set==result]
        logsum = 0
        for feature_index in range(x_train_set.shape[1]):
            filtered_Data_index = filtered_Data[:,feature_index].ravel()
            mean = np.mean(filtered_Data_index)
            std = np.std(filtered_Data_index)+1e-6
            x = test_example[feature_index]
            z = (x-mean)/std
            gaussian = 1/(np.sqrt(2*np.pi)*std)*np.exp(-1/2*((z)**2))
            logsum = logsum+np.log(gaussian)
        logprob = np.log(probabilties[result])+logsum
        probs[result] = np.exp(logprob)
    max_key = max(probs, key=probs.get)
    return max_key

In [74]:
mypredictions = []
for i in range(0,len(x_test_set)):
    test_example= x_test_set[i].ravel()
    predicted = predictions(test_example)
    mypredictions.append(predicted)

In [75]:
accuracy_score(y_test_set,mypredictions)

0.96

In [76]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test_set, mypredictions))
print(classification_report(y_test_set, mypredictions))

[[ 5  0  0]
 [ 0  8  0]
 [ 0  1 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       0.89      1.00      0.94         8
           2       1.00      0.92      0.96        12

    accuracy                           0.96        25
   macro avg       0.96      0.97      0.97        25
weighted avg       0.96      0.96      0.96        25

